name: TuroProjGithubAction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: lint_check.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run Unit Test
        run: ./gradlew test

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test
          path: app/build/reports/tests/testDebugUnitTest/


  package-debug-version:
    needs: [unit-test]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: another-app.apk
          path: app/build/outputs/apk/debug/app-debug.apk

